app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, PasswordField, RadioField, IntegerField, TextAreaField
from wtforms.validators import DataRequired, NumberRange
from ..models import BookType, Warehouse


class Login(FlaskForm):
    account = StringField(u'账号', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[DataRequired()])
    choice = [('student', u"学生"), ('faculty', u"职工")]
    choose = RadioField(u'类别', choices=choice, validators=[DataRequired()], coerce=str)
    submit = SubmitField(u'登录')


class Logon(FlaskForm):
    account = StringField(u'账号', validators=[DataRequired()])
    password1 = PasswordField(u'密码', validators=[DataRequired()])
    password2 = PasswordField(u'密码', validators=[DataRequired()])
    name = StringField(u'名字', validators=[DataRequired()])
    sex = RadioField(u'性别', choices=[('man', u'男'), ('woman', u'女')], validators=[DataRequired()], coerce=str)
    dept = StringField(u'院系', validators=[DataRequired()])
    tel = StringField(u'电话', validators=[DataRequired()])
    email = StringField(u'邮箱', validators=[DataRequired()])
    type = RadioField(u'账号类型', choices=[('student', u'学生'), ('faculty', u'职工')], validators=[DataRequired()],
                      coerce=str)
    submit = SubmitField(u'注册')


class SearchStudentForm(FlaskForm):
    methods = [('student', '学生用户'), ('faculty', '职工用户')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    card = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class SearchFacultyForm(FlaskForm):
    card = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class BorrowForm(FlaskForm):
    methods = [('student', '学生用户'), ('faculty', '职工用户')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    card = StringField(validators=[DataRequired()])
    book_name = StringField(validators=[DataRequired()])
    submit = SubmitField(u'搜索')


class ReturnForm(FlaskForm):
    methods = [('student', '学生用户'), ('faculty', '职工用户')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    card = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class SearchBookForm(FlaskForm):
    methods = [('book_name', '书名'), ('author', '作者'), ('class_name', '类别'), ('isbn', 'ISBN')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    content = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class SearchQueryForm(FlaskForm):
    methods = [('student', '学生用户'), ('faculty', '职工用户')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    methods2 = [('book_name', '书名'), ('uid', '借阅卡号'), ('uname', '读者姓名')]
    method2 = SelectField(choices=methods2, validators=[DataRequired()], coerce=str)

    content = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main
from .forms import Login, Logon, SearchStudentForm, BorrowForm, SearchFacultyForm, SearchBookForm, ReturnForm, \
    SearchQueryForm
from flask import flash, redirect, url_for, session, render_template, request, jsonify
from flask_login import login_user, logout_user, login_required, current_user
import time
from datetime import datetime, date
from .. import db
from ..models import Admin, Student, Faculty, BookType, Warehouse, Book, Query, Record, Inventory, Query_Faculty, \
    Library
import json
from sqlalchemy import or_, and_


# ******************************* 注册登录相关 *******************************
@main.route('/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        if form.choose.data == 'student':
            # print("student被执行")
            user = Student.query.filter_by(Sno=form.account.data, Spassword=form.password.data).first()
            if user is not None:
                login_user(user)
                session['name'] = user.Sname
                session['account_type'] = form.choose.data
                session['uid'] = form.account.data
                print("login---->", user)
                session['admin'] = False
                session['admin_Ano'] = None
        elif form.choose.data == 'faculty':
            user = Faculty.query.filter_by(Fno=form.account.data, Fpassword=form.password.data).first()
            if user is not None:
                admin = Admin.query.filter_by(Fno=form.account.data).first()
                # print('---->', admin)
                if admin is not None:  # 管理员
                    session['admin'] = True
                    session['admin_Ano'] = admin.Ano
                else:
                    session['admin'] = False
                    session['admin_Ano'] = None
                login_user(user)
                session['name'] = user.Fname
                session['account_type'] = form.choose.data
                # print(session['account_type'])
                session['uid'] = form.account.data
                # print("login---->", user)
        else:
            user = None
        if user is None:
            flash(u"用户名或密码错误，请重新输入")
            return redirect(url_for('.login'))
        else:
            current_user.uid = form.account.data
            # print('uid-->', current_user.uid)
            # 登录成功
            # print(session['admin'])
            if session['admin'] == True:
                return redirect(url_for('.index'))
            else:
                return redirect(url_for('.index_common'))

    return render_template('main/login.html', form=form)


@main.route("/logon", methods=['GET', 'POST'])
def logon():
    form = Logon()
    if form.validate_on_submit():
        if form.password1.data != form.password2.data:
            flash(u'请确认密码是否一致！')
        else:
            if form.sex.data == 'man':
                sex = '男'
            else:
                sex = '女'
            today_date = date.today()
            today_str = today_date.strftime("%Y-%m-%d")
            today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
            valid_date = str((int(today_stamp) + 365 * 4 * 86400) * 1000)
            if form.type.data == 'student':
                user = Student(form.account.data, form.name.data, sex, form.dept.data, form.tel.data, form.email.data,
                               today_stamp, valid_date, form.password1.data)
                db.session.add(user)
                db.session.commit()

            elif form.type.data == 'faculty':
                user = Faculty(form.account.data, form.name.data, sex, form.dept.data, '本科', '助教', True, form.tel.data,
                               form.email.data, form.password1.data, today_stamp, valid_date)
                db.session.add(user)
                db.session.commit()

                # 超级管理员
                if user.Fno == 'admin00001':
                    admin = Admin(user.Fno)
                    db.session.add(admin)
                    db.session.commit()

            else:
                flash(u'请完整填写内容！')
                return redirect(url_for('.logon'))
            flash(u'注册成功，请登录!')
            return redirect(url_for('.login'))
    return render_template('main/logon.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash(u'您已退出登录！')
    return redirect(url_for('.login'))


# ******************************* 主页、个人信息 *******************************
@main.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = SearchBookForm()
    return render_template('main/index.html', name=session.get('name'), form=form)


@main.route('/index_common', methods=['GET', 'POST'])
@login_required
def index_common():
    form = SearchBookForm()
    return render_template('main/index-common.html', name=session.get('name'), form=form)


@main.route('/user_info')
@login_required
def user_info():
    # print('id----->', session['uid'])
    if session['account_type'] == 'student':
        user = Student.query.filter_by(Sno=session['uid']).first()
        return render_template('main/user-info-stu.html', user=user, name=session.get('Sname'))
    elif session['account_type'] == 'faculty':
        user = Faculty.query.filter_by(Fno=session['uid']).first()
        return render_template('main/user-info-faculty.html', user=user, name=session.get('Fname'))
    else:
        return render_template('main/index.html')


# ******************************* 学生信息查询 ****************************
@main.route('/search_student', methods=['GET', 'POST'])
@login_required
def search_student():
    form = SearchStudentForm()
    # if session['group'] == 'student':
    #     flash(u'您无权限操作！')
    return render_template('main/search-student.html', name=session.get('name'), form=form)


@main.route('/student', methods=['POST'])
def find_student():
    stu = Student.query.filter_by(Sno=request.form.get('card')).first()
    if stu is None:
        return jsonify([])
    else:

        today_date = date.today()
        today_str = today_date.strftime("%Y-%m-%d")
        today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
        today_stamp = str((int(today_stamp)) * 1000)

        return jsonify([{'name': stu.Sname, 'gender': stu.Ssex, 'dept': stu.Sdept, 'tel': stu.Stel,
                         'email': stu.Semail, 'enroll_date': stu.enroll_date, 'valid_date': stu.valid_date,
                         'debt': False if stu.valid_date < today_stamp else True}])


@main.route('/record', methods=['POST'])
def find_record():
    records = db.session.query(Query).join(Inventory).join(Book).filter(Query.Qname == request.form.get('card')) \
        .with_entities(Query.Midentifiter, Inventory.isbn, Book.Bname, Book.Bauthor, Query.Qbdate,
                       Query.Qrdate, Query.Qvalidity).all()
    data = []
    for record in records:
        start_date = timeStamp(record.Qbdate)
        due_date = timeStamp(record.Qvalidity)
        end_date = timeStamp(record.Qrdate)
        if end_date is None:
            end_date = '未归还'
        item = {'barcode': record.Midentifiter, 'book_name': record.Bname, 'author': record.Bauthor,
                'start_date': start_date, 'due_date': due_date, 'end_date': end_date}
        data.append(item)
    return jsonify(data)


# ******************************* 职工信息查询 ****************************

@main.route('/search_faculty', methods=['GET', 'POST'])
@login_required
def search_faculty():
    form = SearchFacultyForm()
    # if session['group'] == 'student':
    #     flash(u'您无权限操作！')
    return render_template('main/search-faculty.html', name=session.get('name'), form=form)


@main.route('/faculty', methods=['POST'])
def find_faculty():
    faculty = Faculty.query.filter_by(Fno=request.form.get('card')).first()
    if faculty is None:
        return jsonify([])
    else:

        today_date = date.today()
        today_str = today_date.strftime("%Y-%m-%d")
        today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
        today_stamp = str((int(today_stamp)) * 1000)

        return jsonify([{'name': faculty.Fname, 'gender': faculty.Fsex, 'dept': faculty.Fdept, 'tel': faculty.Ftel,
                         'email': faculty.Femail, 'degree': faculty.Fdegree, 'title': faculty.Ftitle,
                         'enroll_date': faculty.enroll_date,
                         'valid_date': faculty.valid_date,
                         'debt': False if faculty.valid_date < today_stamp else True}])


# ******************************* 工具 ****************************
def timeStamp(timeNum):
    if timeNum is None:
        return timeNum
    else:
        timeStamp = float(float(timeNum) / 1000)
        timeArray = time.localtime(timeStamp)
        # print(time.strftime("%Y-%m-%d", timeArray))
        return time.strftime("%Y-%m-%d", timeArray)


# ******************************* 图书管理 *******************************

@main.route('/new_store', methods=['GET', 'POST'])
@login_required
def new_store():
    # print(request.form)
    if request.form:
        data = request.form
        Bno = data["Bno"]
        Bname = data["Bname"]
        Bauthor = data["Bauthor"]
        Bbrief = data["Bbrief"]
        Bpress = data["Bpress"]
        Brank = int(data["Brank"])
        Btype = data["Btype"]
        Wno = data["Wno"]
        Bshelf = data["Bshelf"]
        Bnumber = data["Bnumber"]
        Bdate = data["Bdate"]
        Bnote = data["Bnote"]
        book = Book(Bno=Bno, Bname=Bname, Bauthor=Bauthor, Bbrief=Bbrief,
                    Bpress=Bpress, Brank=Brank, Btype=Btype, Wno=Wno, Bshelf=Bshelf, Bdate=Bdate, Bnote=Bnote,
                    Bnumber=Bnumber)
        record = Record(Bno, 1, "新建图书")
        db.session.add(book)
        db.session.add(record)
        db.session.commit()

        for i in range(int(Bnumber)):
            inventory = Inventory()

app/templates/main/base-user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../static/layui/css/layui.css">
    <link rel="stylesheet" href="../static/login.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <style>
          .alert{position:relative;padding:.75rem 1.25rem;margin-bottom:1rem;border:1px solid transparent;border-radius:.25rem}
          .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
          .alert-warning{color:#856404;background-color:#fff3cd;border-color:#ffeeba}
          .close{float:right;font-size:1.5rem;font-weight:700;line-height:1;color:#000;text-shadow:0 1px 0 #fff;opacity:.5}
          .close:focus,.close:hover{color:#000;text-decoration:none;opacity:.75}
          .close:not(:disabled):not(.disabled){cursor:pointer}
          button.close{padding:0;background-color:transparent;border:0;-webkit-appearance:none}
          .close{padding:1rem;margin:-1rem -1rem -1rem auto}
          .alert-dismissible .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
    </style>
</head>
<body>
<div class="layui-layout layui-layout-admin">
<div class="layui-header layui-bg-molv">
  <div class="layui-logo"><span style="color:#F0F0F0;font-size: large">图书管理系统</span></div>
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.login') }}">登录</a></li>
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.logon') }}">注册</a></li>
    </ul>
  </div>
</div>
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
    </div>
{% endfor %}
</div>

{% block body %}
{% endblock %}

<script src="../static/layui/layui.js"></script>
<script type="text/javascript">
    layui.use('form', function () {
        var form = layui.form;

    });
    layer.open({
        content: '浏览器滚动条已锁',
        scrollbar: true
    });
</script>
{% block script %}{% endblock %}
</body>
</html>

app/templates/main/base_common.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../static/layui/css/layui.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <style>
        .alert {
            position: relative;
            padding: .75rem 1.25rem;
            margin-bottom: 1rem;
            border: 1px solid transparent;
            border-radius: .25rem
        }

        body {
            overflow-y: scroll;
        }

        /* 禁止刷新后出现横向滚动条 */
        .close {
            position: absolute;
            top: 0;
            right: 0;
            padding: .75rem 1.25rem;
            color: inherit
        }

        .alert-warning {
            color: #856404;
            background-color: #fff3cd;
            border-color: #ffeeba
        }

        .close {
            float: right;
            font-size: 1.5rem;
            font-weight: 700;
            line-height: 1;
            color: #000;
            text-shadow: 0 1px 0 #fff;
            opacity: .5
        }

        .close:focus, .close:hover {
            color: #000;
            text-decoration: none;
            opacity: .75
        }

        .close:not(:disabled):not(.disabled) {
            cursor: pointer
        }

        button.close {
            padding: 0;
            background-color: transparent;
            border: 0;
            -webkit-appearance: none
        }

        .close {
            padding: 1rem;
            margin: -1rem -1rem -1rem auto
        }

        .alert-dismissible .close {
            position: absolute;
            top: 0;
            right: 0;
            padding: .75rem 1.25rem;
            color: inherit
        }
    </style>
    {% block head %}{% endblock %}
    <style>{% block style %}{% endblock %}</style>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <a href="{{ url_for('main.index_common') }}">
            <div class="layui-logo">图书管理系统</div>
        </a>


        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <img src="../static/icon.jpg" class="layui-nav-img">
                    {{ name }}
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="{{ url_for('main.user_info') }}">个人信息</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item"><a href="{{ url_for('main.logout') }}">退出登录</a></li>
        </ul>
    </div>

    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item">
                <li class="layui-nav-item">
                    <a class="" href="javascript:;">普通用户功能</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{{ url_for('main.search_book') }}">图书查询</a></dd>
                    </dl>
                </li>

            </ul>
        </div>
    </div>

    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div class="layui-card layui-row layui-col-space10" style="margin:15px 10px;width:100%;">
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            {% block card %}{% endblock %}
            <div class="layui-card-body">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="layui-footer">
        数据库课设-图书管理系统
    </div>
</div>
<script src="../static/layui/layui.js"></script>
<script>

    layui.use('element', function () {
        var element = layui.element;
        element.init();
    });
</script>

{% block script %}

{% endblock %}

</body>
</html>

app/templates/main/book-note.html
{% extends 'main/base.html' %}
{% block title %}图书操作日志

{% endblock %}

{% block card %}
    <div class="layui-card-header">
        <h2>图书操作日志</h2>
    </div>

{% endblock %}
{% block body %}


    <div>
        <table class="layui-hide" id="test" lay-filter="test"></table>
    </div>
     <script type="text/html" id="toolbarDemo">
        <div class="layui-form-item">
            <div class="layui-inline">
                <div class="layui-input-block">
                    <input type="text" name="title" lay-verify="title" autocomplete="off" placeholder="关键字搜索"
                           class="layui-input" id="searchContent">
                </div>
            </div>
            <div class="layui-inline">
                <button class="layui-btn layui-btn-sm" lay-event="search">搜索</button>
            </div>
        </div>
     </script>
{% endblock %}
{% block script %}
    <script>
        layui.use(['table', 'layer', 'form'], function () {
            var table = layui.table;
            table.render({
                elem: '#test'
                , id: 'listware'
                , url: "{{ url_for('main.select_book_note') }}"
                , where: {
                    data: "all"
                }
                , toolbar: '#toolbarDemo'
                , title: '书库日志表'
                , contentType: 'application/json'
                , totalRow: true
                , width: 700
                , cols: [[
                    {type: 'checkbox', fixed: 'left'}
                    , {
                        field: 'Rno',
                        title: 'ID号',
                        fixed: 'left',
                        unresize: true,
                        sort: true,
                        totalRowText: '合计'
                    }
                    , {field: 'Bno', title: '国际标准书号', sort: true}
                    , {field: 'Ano', title: '管理员号', edit: 'text'}
                    , {field: 'Rdate', title: '操作日期', edit: 'text'}
                    , {field: 'Rnote', title: '备注', edit: 'text'}
                ]]
                , page: true //是否显示分页
                , limits: [3, 5, 10]
                , limit: 5 //每页默认显示的数量
            });
            table.on('toolbar(test)', function (obj) {
                switch (obj.event) {
                    case 'search':
                        table.reload("listware", {
                            page: {
                                curr: 1 //重新从第 1 页开始
                            },
                            where: {
                                data: $('#searchContent').val()
                            }
                        }, 'data');
                        break;
                }
            });
        });
    </script>
{% endblock %}

app/templates/main/logon.html
{% extends "main/base-user.html" %}
{% block title %}欢迎使用图书管理系统{% endblock %}

{% block body %}
<div class="login-main">

    <header class="layui-elip">注册</header>
    <form class="layui-form" method="post">
        {{ form.csrf_token }}
        <div class="layui-input-inline">
            {{ form.account(class="layui-input",placeholder="账号") }}
        </div>
        <div class="layui-input-inline">
            {{ form.password1(class="layui-input",placeholder="输入密码") }}
        </div>
        <div class="layui-input-inline">
            {{ form.password2(class="layui-input",placeholder="确认密码") }}
        </div>
        <div class="layui-input-inline">
            {{ form.name(class="layui-input",placeholder="你的名字") }}
        </div>
        <div class="layui-form-radio">
            {{ form.sex(class="layui-input-block")}}
        </div>
        <div class="layui-input-inline">
            {{ form.dept(class="layui-input",placeholder="院系") }}
        </div>
        <div class="layui-input-inline">
            {{ form.tel(class="layui-input",placeholder="电话") }}
        </div>
        <div class="layui-input-inline">
            {{ form.email(class="layui-input",placeholder="邮箱") }}
        </div>
        <div class="layui-form-radio">
            {{ form.type(class="layui-input-block")}}
        </div>
        <div class="layui-input-inline login-btn">
            {{ form.submit(class="layui-btn") }}
        </div>
        <hr/>
    </form>

</div>
{% endblock %}

app/templates/main/search-student.html
{% extends "main/base.html" %}
{% block title %}查询学生信息{% endblock %}

{% block card %}<div class="layui-card-header"><h2>查询学生信息</h2></div>{% endblock %}
{% block body %}
    <form class="layui-form" method="post" id="searchForm">
    <!--{{ form.csrf_token }}-->
        <div class="layui-form-item">
            <div class="layui-inline">
                <div class="layui-row layui-col-space10">
                    <div class="layui-col-md4">
                        <label style="font-size: medium;width: 180px;" class="layui-form-label">请输入学生借阅卡号码：</label>
                    </div>
                    <div class="layui-col-md5">
                        <div class="layui-input-inline">
                            {{ form.card(class="layui-input", id="card") }}
                        </div>
                    </div>
                    <div class="layui-col-md2">
                        <div class="layui-input-inline">{{ form.submit(class="layui-btn", id="search") }}</div>

                    </div>
                </div>
            </div>

        </div>
    </form>
    <div id="info">
    <p>
        <span>姓名：<span id="name"></span></span>
        <span style="margin-left: 140px;">性别：<span id="gender"></span></span>
        <span style="margin-left: 120px;">有效期至：<span id="valid_date"></span></span>
        <span style="margin-left: 140px;">是否有效：<span id="debt"></span></span>
    </p>
    </div>
    <div id="remove">
    <table lay-even id="result" lay-filter="re">
      <thead>
        <tr>
          <th lay-data="{field:'barcode', width:160}">图书编号</th>
          <th lay-data="{field:'book_name', width:200}">书名</th>
          <th lay-data="{field:'author', width:140}">作者</th>
          <th lay-data="{field:'start_date', width:200}">起始日期</th>
          <th lay-data="{field:'due_date', width:200}">应还日期</th>
          <th lay-data="{field:'end_date'}">还书日期</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>
    </div>
    <table id="test" lay-filter="test"></table>

{% endblock %}

{% block script %}
    <script>
    layui.use(['form','table','jquery'], function(){
        var form = layui.form;
        var table = layui.table;
        var $ = layui.$;

        table.init('re', {
              height: 390
              ,limit: 7
              ,page: true
        });

        $(document).ready(function(){
            $('#search').on('click',function () {
                var form = new FormData(document.getElementById("searchForm"));
                if($('#card').val() === ""){
                    layui.use('layer', function(){
                        var layer = layui.layer;

                        layer.msg('请填写查询内容',{time: 800});
                    });
                }
                else{
                    $.ajax({
                        url:"{{ url_for('main.find_student') }}",
                        type:"post",
                        data:form,
                        processData:false,
                        contentType:false,
                        success:function(data){
                            $("#name").empty();
                            $("#gender").empty();
                            $("#valid_date").empty();
                            $("#debt").empty();
                            if(data.length !== 0){
                                $("#name").append(data[0].name);
                                $("#gender").append(data[0].gender);
                                $("#valid_date").append(data[0].valid_date);
                                if(data[0].debt === false){
                                    $("#debt").append('否');
                                }
                                else{
                                    $("#debt").append('是');
                                }

                                $.ajax({
                                    url:"{{ url_for('main.find_record') }}",
                                    type:"post",
                                    data:form,
                                    processData:false,
                                    contentType:false,
                                    success:function(data){
                                        if (data.length !== 0){
                                            $('#remove').remove();
                                            table.render({
                                                elem: '#test'
                                                ,data:data
                                                ,cols: [[
                                                    {field:'barcode', title:'图书编号', width:160}
                                                    ,{field:'book_name', title:'书名', width:200}
                                                    ,{field:'author', title:'作者', width:140}
                                                    ,{field:'start_date', title:'起始日期', width:200}
                                                    ,{field:'due_date', title:'应还日期', width:200}
                                                    ,{field:'end_date', title:'还书日期'}
                                                ]]
                                                ,page: true
                                                ,height: 390
                                                ,limit: 7
                                                ,response: {
                                                    statusCode: 200 //重新规定成功的状态码为 200，table 组件默认为 0
                                                }
                                                ,parseData: function(data){ //将原始数据解析成 table 组件所规定的数据
                                                    return {
                                                        "code": data.status, //解析接口状态
                                                        "msg": data.message, //解析提示文本
                                                        "count": data.total, //解析数据长度
                                                        "data": data.rows.item //解析数据列表
                                                    };
                                                }
                                            });
                                        }
                                        else{
                                            layui.use('layer', function(){
                                            var layer = layui.layer;

                                            layer.msg('没有任何借阅记录',{time: 1000});
                                            });
                                        }
                                    }
                                });

                            }
                            else {
                                layui.use('layer', function(){
                                var layer = layui.layer;

                                layer.msg('找不到该学生！',{time: 1000});
                                });
                            }
                        }
                    });

                }
                return false;
            });
        });
    });
    </script>
{% endblock %}